name: Java CI 04 with Checkstyle
run-name: ${{ github.actor }} checks Java Style

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Run maven unit tests
        steps:
          - name: Checkout code
            uses: actions/checkout@v2
          - name: Set up JDK
            uses: actions/setup-java@v2
            with:
              java-version: 19
          - name: Build and test
            run: mvn test
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: 'github-check'
          tool_name: 'testtool'
          level: 'error'
          fail_on_error: true
