name: Automatic Unit Test
run-name: Unit Tests
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 19
          distribution: 'adopt'
      - name: Build and test
        run: mvn test
      - name: Upload test report
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: /target/surefire-reports/at.fhj.iit.CalculatorImplTest.txt
#      - name: Test Report
#        uses: dorny/test-reporter@v1
#        if: success() || failure()
#        with:
#          name: Test Results
#          path: target/surefire-reports/TEST-TestSuite.xml
#          reporter: java-junit
#          java-version: 19
#      - name: Upload target folder
#        uses: actions/upload-artifact@v2
#        with:
#          name: target
#          path: |
#            ${{ github.workspace }}/target
#            ${{ github.workspace }}/reports
